// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkg3WsZwiwjxVpprBCkbzIyl7Nw-Si0jk',
    appId: '1:1048431871160:web:3c6464c49661348524204d',
    messagingSenderId: '1048431871160',
    projectId: 'flutter-moon',
    authDomain: 'flutter-moon.firebaseapp.com',
    storageBucket: 'flutter-moon.firebasestorage.app',
    measurementId: 'G-DDJMSBM1H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH6juyV_EXgbxLNGIBpGn8s04m31jnnGc',
    appId: '1:1048431871160:android:adcfa96114da2e6124204d',
    messagingSenderId: '1048431871160',
    projectId: 'flutter-moon',
    storageBucket: 'flutter-moon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqh9rRugt4yEPQt-lSHH0fFCuVECFcGJw',
    appId: '1:1048431871160:ios:3d0de0eed565b8ce24204d',
    messagingSenderId: '1048431871160',
    projectId: 'flutter-moon',
    storageBucket: 'flutter-moon.firebasestorage.app',
    iosBundleId: 'com.example.moonAplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqh9rRugt4yEPQt-lSHH0fFCuVECFcGJw',
    appId: '1:1048431871160:ios:3d0de0eed565b8ce24204d',
    messagingSenderId: '1048431871160',
    projectId: 'flutter-moon',
    storageBucket: 'flutter-moon.firebasestorage.app',
    iosBundleId: 'com.example.moonAplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkg3WsZwiwjxVpprBCkbzIyl7Nw-Si0jk',
    appId: '1:1048431871160:web:19fdfa03a9196c5224204d',
    messagingSenderId: '1048431871160',
    projectId: 'flutter-moon',
    authDomain: 'flutter-moon.firebaseapp.com',
    storageBucket: 'flutter-moon.firebasestorage.app',
    measurementId: 'G-0NCWKWHQSS',
  );
}
